### ISSUE TITLE
Spock-reports falsely reports failures where Spock does not

### ISSUE THREAD

**Issue by oliverkuntze** [renatoathaydes/spock-reports#179]
Hi Renato,

thanks for your great spock extension.

I have the following test code:
```
@Unroll
    def "a sum should be correctly calculated (#summand1 + #summand2)"() {
        given: "summmand 1 = #summand1 and summand 2 = #summand2"
        def int1 = new Integer(summand1)
        def int2 = new Integer(summand2)

        when: "the sum is calculated"
        def result = helloWorld.sum(int1, int2)

        then: "the result should be correct"
        reportInfo "The expected sum is ${sum}."
        result == sum

        where:
        summand1 | summand2 || sum
        0        | 0        || 0
        1        | 1        || 2
    }
```

Executing this spec through regular spock I get 0 failures as expected.

However spock-reports reports 100% success rate on the specifications summary page but 50% success rate for the beforementioned specification.
The error report for "a sum should be correctly calculated (1 + 1)" states:
```
Condition not satisfied:

result == sum
|      |  |
0     |  2
       false
```

The value for the variable result seems to be taken from the first "a sum should be correctly calculated (0 + 0)" run.

Seems like a bug.

It also happens when I don't use the unroll annotation and the the decision table but put the code in 2 feature methods.

Any idea?

Cheers 
Oliver

**Comment by oliverkuntze** [comment]
Hi Renato,

I just found out that this behaviour only occurs in special situations.

I have now organized my POM into profiles and while testing the reorganization I realized that spock-reports correctly reports the test results in my default profile but did not report them correctly when I had the profile for mutation testing active.

I am using pitest for mutation testing. This somehow messes up the spock-report results.

Any ideas?

**Comment by renatoathaydes** [comment]
Probably related to https://github.com/renatoathaydes/spock-reports/issues/173
Can you check? That issue is fixed but not released yet.

**Comment by oliverkuntze** [comment]
Will try to check if the fix does the job. Will first have to read myself a bit into gradle, expecially how to install an artifact into ky local maven repo using gradle.

**Comment by oliverkuntze** [comment]
I just tested against the ```next``` branch. The bug unfortunately still persists.

**Comment by oliverkuntze** [comment]
Here is my hello world example you can use to reproduce the situation. Please activate the ```pitest``` profile.
[testing-testbed-maven.zip](https://github.com/renatoathaydes/spock-reports/files/3696637/testing-testbed-maven.zip)

**Comment by oliverkuntze** [comment]
Hi @renatoathaydes . Did you have the time to look into the issue. We would like to switch from fitnesse to spock reports for our e2e tests. But this issue is a real show stopper for us.

**Comment by renatoathaydes** [comment]
I have been on vacation for a month, but am now back... didn't have time to look into this during my time off, but I will try to find out what's going on soon.

Just to make sure I understand it: you're using a mutation test framework (pitest) as well as Spock. You believe Spock itself reports the test results correctly ( I guess you look at the Gradle reports, or just JUnit reports?), but not spock-reports - spock-reports reports some failure which shouldn't be there, even though there's an error in the logs (I assume this is because pitest verifies that changing implementation code does cause a failure?). Is this correct?

**Comment by renatoathaydes** [comment]
I enabled logging so I could see what spock-reports is seeing, first without pitest and then with it.

Without PiTest:

```
[main] DEBUG com.athaydes.spockframework.report.SpecInfoListener - Before spec: de.db.sandbox.HelloWorldSpec
[main] DEBUG com.athaydes.spockframework.report.SpecInfoListener - Before feature: a sum should be correctly calculated (#summand1 + #summand2)
[main] DEBUG com.athaydes.spockframework.report.SpecInfoListener - Before iteration: a sum should be correctly calculated (0 + 0)
[main] DEBUG com.athaydes.spockframework.report.SpecInfoListener - After iteration: a sum should be correctly calculated (0 + 0)
[main] DEBUG com.athaydes.spockframework.report.SpecInfoListener - Before iteration: a sum should be correctly calculated (1 + 1)
[main] DEBUG com.athaydes.spockframework.report.SpecInfoListener - After iteration: a sum should be correctly calculated (1 + 1)
[main] DEBUG com.athaydes.spockframework.report.SpecInfoListener - After feature: a sum should be correctly calculated (#summand1 + #summand2)
[main] DEBUG com.athaydes.spockframework.report.SpecInfoListener - After spec: de.db.sandbox.HelloWorldSpec
```

With PiTest, I see spock-reports being initialized a few times (looks like PiTest spans separate processes to run the test classes) but can't see the logs because PiTest does not seem to be propagating system properties to the forked processes (the logger is configured via a system property) - but that's not really necessary, as it's clear that PiTest is just running the Spock tests in different processes, several times, messing up the reports.

Unfortunately, there's no good way to know you're executing tests in the background but the results should be ignored... the only thing I can think of is to use a different test runner when PiTest is enabled, rather than Spock's `Sputnik` but that would be quite tricky to do right.

In your first message, you said that `Executing this spec through regular spock I get 0 failures as expected.`. Well, from what I see, you also get `Tests run: 0, Failures: 0, Errors: 0, Skipped: 0`? I don't think Spock or even JUnit could report the right thing when you use PiTest - only PiTest "knows" what it's doing with the test classes, so maybe using their report is enough?

**Comment by oliverkuntze** [comment]
Hi Renato. Thanks for the update. I will have a look at it and get back to you next week.
Cheers Oliver

**Comment by renatoathaydes** [comment]
Closing ticket for now. Please open a more specific issue if you still feel we must fix something.
