### ISSUE TITLE
Tests with parameters but without @Unroll will have extraInfo all grouped to first iteration

### ISSUE THREAD

**Issue by Frankie0701** [renatoathaydes/spock-reports#244]
We notice after upgrade to 2.3.2-groovy-3.0, our tests without @Unroll that has extarInfo for each iteration will have all extraInfo only displayed in first iteration, and leave rest iterations' extraInfo blank.
For example, with following test, you can see the spec template screenshot that extra info are displayed in first iteration including all info from the rest iterations. This works fine before our upgrade from 1.7.1
`def 'test without unroll'() {`
`    when:`
`    reportInfo("extra info for iteration: " + input)`
` `
`    then:`
`    true`
` `
`    where:`
`    input << [1, 2]`
`}`
![image](https://user-images.githubusercontent.com/58716817/217430042-7fff5266-72c9-494d-86fa-1e0bc73ad52f.png)

**Comment by Frankie0701** [comment]
Hi @renatoathaydes , I want to create a PR for this, but I don't have the permission to create a branch for this, could you help me with it? thanks

**Comment by renatoathaydes** [comment]
Done.
```
git fetch origin
git checkout 244-tests-with-parameters-but-without-unroll-will-have-extrainfo-all-grouped-to-first-iteration
```

**Comment by Frankie0701** [comment]
Sorry @renatoathaydes , I still get 403 when push my changes to `244-tests-with-parameters-but-without-unroll-will-have-extrainfo-all-grouped-to-first-iteration`, I have double checked my personal access token, it should be fine, workflow is included. What might go wrong?

**Comment by Frankie0701** [comment]
Hi @renatoathaydes,
Thx for the review, do you have any ETA when will next release happen?

**Comment by renatoathaydes** [comment]
I've found a reliable way to know when a spec is rolledup/unrolled, which fixed the issue for good...

I reverted the change to the main HTML report creator so that we do not prepend text to each "extra info" message. That was not needed.

But there are a few more bugs I want to fix before the next release. Hoping to release within a few days.

**Comment by Frankie0701** [comment]
Hi @renatoathaydes ,
I saw you did a release of [2.5.0-groovy-4.0](https://github.com/renatoathaydes/spock-reports/releases/tag/2.5.0-groovy-4.0) last week, will you do another one for 2.3.X-groovy-3.0? for us, there is some extra work to do to upgrade to groovy-4, it would be easier for us to have a groovy-3 compatible version

**Comment by renatoathaydes** [comment]
It was not hard to do it, so I released `2.5.0-groovy-3.0` on Maven Central. It passed all tests on Java 8, 11, and 17, and the only differences between that and `2.5.0-groovy-4.0` are the dependency versions!

It may take a few hours for Maven Central to make the new version available.

**Comment by Frankie0701** [comment]
Hi @renatoathaydes ,
many thx for the release. Tried in our project, works perfect! thanks again for the effort!
